# Copyright 2025 Lewa-Reka & Harvey Dent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "DC Temperature"
    register_type: holding
    address: 90
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1
    disabled_by_default: true
    value_type: S_WORD
    filters:
      - offset: -1000
      - multiply: 0.1
    icon: "mdi:thermometer"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "AC Temperature"
    register_type: holding
    address: 91
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - offset: -1000
      - multiply: 0.1
    icon: "mdi:thermometer"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output Frequency"
    register_type: holding
    address: 193
    unit_of_measurement: "Hz"
    device_class: frequency
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output L1 Current"
    register_type: holding
    address: 164
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:current-ac"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output L2 Current"
    register_type: holding
    address: 165
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:current-ac"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output L1 Power"
    register_type: holding
    address: 173
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:solar-power"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output L2 Power"
    register_type: holding
    address: 174
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:solar-power"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output Power"
    id: output_power
    register_type: holding
    address: 175
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:solar-power"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output L1 Voltage"
    register_type: holding
    address: 154
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Output L2 Voltage"
    register_type: holding
    address: 155
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"
